/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Playlist {
  'id' : PlaylistId,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'songIds' : Array<SongId>,
}
export type PlaylistId = bigint;
export interface PlaylistInput { 'name' : string, 'description' : string }
export interface Song {
  'id' : SongId,
  'title' : string,
  'duration' : bigint,
  'album' : string,
  'lyrics' : string,
  'createdAt' : Timestamp,
  'audioUrl' : string,
  'coverArtUrl' : string,
  'artist' : string,
}
export type SongId = bigint;
export interface SongInput {
  'title' : string,
  'duration' : bigint,
  'album' : string,
  'lyrics' : string,
  'audioUrl' : string,
  'coverArtUrl' : string,
  'artist' : string,
}
export interface SongPublic {
  'id' : SongId,
  'title' : string,
  'duration' : bigint,
  'album' : string,
  'lyrics' : string,
  'createdAt' : Timestamp,
  'audioUrl' : string,
  'coverArtUrl' : string,
  'artist' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionTier = { 'premium' : null } |
  { 'free' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addSong' : ActorMethod<[SongInput], Song>,
  'addSongToPlaylist' : ActorMethod<[PlaylistId, SongId], [] | [Playlist]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmPremiumUpgrade' : ActorMethod<[string], boolean>,
  'createCheckoutSession' : ActorMethod<[string, string], string>,
  'createPlaylist' : ActorMethod<[PlaylistInput], Playlist>,
  'deletePlaylist' : ActorMethod<[PlaylistId], boolean>,
  'deleteSong' : ActorMethod<[SongId], boolean>,
  'editSong' : ActorMethod<[SongId, SongInput], [] | [Song]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlaylist' : ActorMethod<[PlaylistId], [] | [Playlist]>,
  'getSong' : ActorMethod<[SongId], [] | [SongPublic]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserTier' : ActorMethod<[], SubscriptionTier>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listMyPlaylists' : ActorMethod<[], Array<Playlist>>,
  'listSongs' : ActorMethod<[], Array<SongPublic>>,
  'removeSongFromPlaylist' : ActorMethod<[PlaylistId, SongId], [] | [Playlist]>,
  'saveCallerUserProfile' : ActorMethod<[string], UserProfile>,
  'searchSongs' : ActorMethod<[string], Array<SongPublic>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePlaylist' : ActorMethod<[PlaylistId, PlaylistInput], [] | [Playlist]>,
  'upgradeUserTier' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];