/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SongInput = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'lyrics' : IDL.Text,
  'audioUrl' : IDL.Text,
  'coverArtUrl' : IDL.Text,
  'artist' : IDL.Text,
});
export const SongId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Song = IDL.Record({
  'id' : SongId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'lyrics' : IDL.Text,
  'createdAt' : Timestamp,
  'audioUrl' : IDL.Text,
  'coverArtUrl' : IDL.Text,
  'artist' : IDL.Text,
});
export const PlaylistId = IDL.Nat;
export const UserId = IDL.Principal;
export const Playlist = IDL.Record({
  'id' : PlaylistId,
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'songIds' : IDL.Vec(SongId),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlaylistInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const SubscriptionTier = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tier' : SubscriptionTier,
});
export const SongPublic = IDL.Record({
  'id' : SongId,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'lyrics' : IDL.Text,
  'createdAt' : Timestamp,
  'audioUrl' : IDL.Text,
  'coverArtUrl' : IDL.Text,
  'artist' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addSong' : IDL.Func([SongInput], [Song], []),
  'addSongToPlaylist' : IDL.Func([PlaylistId, SongId], [IDL.Opt(Playlist)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPremiumUpgrade' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createCheckoutSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createPlaylist' : IDL.Func([PlaylistInput], [Playlist], []),
  'deletePlaylist' : IDL.Func([PlaylistId], [IDL.Bool], []),
  'deleteSong' : IDL.Func([SongId], [IDL.Bool], []),
  'editSong' : IDL.Func([SongId, SongInput], [IDL.Opt(Song)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlaylist' : IDL.Func([PlaylistId], [IDL.Opt(Playlist)], ['query']),
  'getSong' : IDL.Func([SongId], [IDL.Opt(SongPublic)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserTier' : IDL.Func([], [SubscriptionTier], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'listSongs' : IDL.Func([], [IDL.Vec(SongPublic)], ['query']),
  'removeSongFromPlaylist' : IDL.Func(
      [PlaylistId, SongId],
      [IDL.Opt(Playlist)],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [UserProfile], []),
  'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(SongPublic)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePlaylist' : IDL.Func(
      [PlaylistId, PlaylistInput],
      [IDL.Opt(Playlist)],
      [],
    ),
  'upgradeUserTier' : IDL.Func([], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SongInput = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'lyrics' : IDL.Text,
    'audioUrl' : IDL.Text,
    'coverArtUrl' : IDL.Text,
    'artist' : IDL.Text,
  });
  const SongId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Song = IDL.Record({
    'id' : SongId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'lyrics' : IDL.Text,
    'createdAt' : Timestamp,
    'audioUrl' : IDL.Text,
    'coverArtUrl' : IDL.Text,
    'artist' : IDL.Text,
  });
  const PlaylistId = IDL.Nat;
  const UserId = IDL.Principal;
  const Playlist = IDL.Record({
    'id' : PlaylistId,
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'songIds' : IDL.Vec(SongId),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlaylistInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const SubscriptionTier = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tier' : SubscriptionTier,
  });
  const SongPublic = IDL.Record({
    'id' : SongId,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'lyrics' : IDL.Text,
    'createdAt' : Timestamp,
    'audioUrl' : IDL.Text,
    'coverArtUrl' : IDL.Text,
    'artist' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addSong' : IDL.Func([SongInput], [Song], []),
    'addSongToPlaylist' : IDL.Func(
        [PlaylistId, SongId],
        [IDL.Opt(Playlist)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPremiumUpgrade' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createCheckoutSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createPlaylist' : IDL.Func([PlaylistInput], [Playlist], []),
    'deletePlaylist' : IDL.Func([PlaylistId], [IDL.Bool], []),
    'deleteSong' : IDL.Func([SongId], [IDL.Bool], []),
    'editSong' : IDL.Func([SongId, SongInput], [IDL.Opt(Song)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlaylist' : IDL.Func([PlaylistId], [IDL.Opt(Playlist)], ['query']),
    'getSong' : IDL.Func([SongId], [IDL.Opt(SongPublic)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserTier' : IDL.Func([], [SubscriptionTier], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'listSongs' : IDL.Func([], [IDL.Vec(SongPublic)], ['query']),
    'removeSongFromPlaylist' : IDL.Func(
        [PlaylistId, SongId],
        [IDL.Opt(Playlist)],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [UserProfile], []),
    'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(SongPublic)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePlaylist' : IDL.Func(
        [PlaylistId, PlaylistInput],
        [IDL.Opt(Playlist)],
        [],
      ),
    'upgradeUserTier' : IDL.Func([], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };